set -l nord0 2e3440
set -l nord1 3b4252
set -l nord2 434c5e
set -l nord3 4c566a
set -l nord4 d8dee9
set -l nord5 e5e9f0
set -l nord6 eceff4
set -l nord7 8fbcbb
set -l nord8 88c0d0
set -l nord9 81a1c1
set -l nord10 5e81ac
set -l nord11 bf616a
set -l nord12 d08770
set -l nord13 ebcb8b
set -l nord14 a3be8c
set -l nord15 b48ead

set -g fish_color_normal $nord4
set -g fish_color_command $nord9
set -g fish_color_quote $nord14
set -g fish_color_redirection $nord9
set -g fish_color_end $nord6
set -g fish_color_error $nord11
set -g fish_color_param $nord4
set -g fish_color_comment $nord3
set -g fish_color_match $nord8
set -g fish_color_search_match $nord8
set -g fish_color_operator $nord9
set -g fish_color_escape $nord13
set -g fish_color_cwd $nord8
set -g fish_color_autosuggestion $nord6
set -g fish_color_user $nord4
set -g fish_color_host $nord9
set -g fish_color_cancel $nord15
set -g fish_pager_color_prefix $nord13
set -g fish_pager_color_completion $nord6
set -g fish_pager_color_description $nord10
set -g fish_pager_color_progress $nord12
set -g fish_pager_color_secondary $nord1
